name: warg-server

services:
  fix-permission:
    image: busybox
    command: ["sh", "-c", "chown -R 1000:1000 /var/lib/warg-server/data"]
    volumes:
      - content:/var/lib/warg-server/data

  api:
    build: .
    develop:
      watch:
        - path: .
          action: rebuild
    environment:
      WARG_OPERATOR_KEY: ecdsa-p256:I+UlDo0HxyBBFeelhPPWmD+LnklOpqZDkrFP5VduASk=
      WARG_NAMESPACE: example
    ports:
      - 8090:8090
    volumes:
      - content:/var/lib/warg-server/data
    depends_on:
      fix-permission:
        condition: service_completed_successfully

volumes:
  content:
