name: warg-server

# - docker compose down --rmi all && docker volume prune -a
# docker compose up --remove-orphans --force-recreate

services:

  api:
    build: .
    develop:
      watch:
        - path: .
          action: rebuild
    environment:
      WARG_OPERATOR_KEY: ecdsa-p256:I+UlDo0HxyBBFeelhPPWmD+LnklOpqZDkrFP5VduASk=
      WARG_NAMESPACE: example
      WKG_REGISTRY: http://localhost:8090
      WARG_CONTENT_BASE_URL: http://localhost:8090
      WARG_LISTEN: 0.0.0.0:8090
      WARG_VERBOSE: 1
    ports:
      - 8090:8090
    command: ["--rm"]
