name: warg-server

services:
  fix-permission:
    image: busybox
    command: ["sh", "-c", "chown -R 1000:1000 /var/lib/warg-server/data"]
    volumes:
      - content2:/var/lib/warg-server/data

  registry:
    image: registry:3.0.0
    container_name: oci-registry
    # environment:
      # - OTEL_TRACES_EXPORTER=none
      # - OTEL_SDK_DISABLED=true
    ports:
      - 5000:5000

  api:
    build: .
    develop:
      watch:
        - path: .
          action: rebuild
    environment:
      WARG_OPERATOR_KEY: ecdsa-p256:I+UlDo0HxyBBFeelhPPWmD+LnklOpqZDkrFP5VduASk=
      WARG_NAMESPACE: example
      WKG_REGISTRY: http://registry:5000
      WARG_CONTENT_BASE_URL: http://localhost:8090
      WARG_LISTEN: 0.0.0.0:8090
      WARG_VERBOSE: 1
      WKG_OCI_INSECURE: "localhost,127.0.0.1"
    ports:
      - 8090:8090
    volumes:
      - content2:/var/lib/warg-server/data
    depends_on:
      - fix-permission
      - registry

volumes:
  content2:
